.TH PACHIST 8 pachist\-0.1.3
.SH NAME
pachist \- a simple tool to view history of installed packages
.SH SYNOPSIS
.B pachist
.RB [ \-d ]
.RB [ \-h ]
.RB [ \-n ]
.RB [ \-q ]
.RB [ \-v ]
.RB [ \-V ]
.RB [ \-\-warn ]
.RI [ <number> ]
.SH DESCRIPTION
.B pachist
is a small program written in bash to show installed package history in
Arch Linux. It can be used by it's own or even better ran directly after 
another command like 'yaourt -Syua --devel --noconfirm && pachist'. The 
verbose option can sometimes be important as it show install messages
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-date\fR
Show output from a specific date. It rely on the 'date --date' command and can handle
pretty much the same formats. For more info check 'man date' or 'info date'. The syntax
is '--date "<arg>"' where the arguments comes directly after the option incapsulated 
by quotation marks.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show a brief help.
.TP
\fB\-n\fR, \fB\-\-num\fR
Show line numbers. It will put a number infront of every line making it easier
to see which lines you want to output. Good in combination with the -q flag.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Show less information. It will show only the package names which is good if you
want to pipe it's output with pacman. 
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show install messages. Like recomended or necessary steps that needs to be taken.
.TP
\fB\-V\fR, \fB\-\-version\fR
Show current version.
.TP
\ \ \ \ \fB\-\-warn\fR
Not as verbose as the '-v' option. Just to show warning messages.
.TP
\fI<number>\fR
The number of lines to show.

It also have support to show range of lines. The syntax is either <n> for total number 
of lines or <n>,<n> for a range were the first number before the comma tells which line
from the bottom to start with and the number after the comma describes the total number
of lines to show. It can be very usefull together with the \fB-q\fR flag.
.SH EXAMPLES
pachist -v 50
.TP
yaourt -Syua --devel --noconfirm && pachist -v 50
.TP
pachist --date 'yesterday' 
.TP
pachist -q 22 
.TP
pachist -q 3,8 | pacman -R -
.SH CUSTOMIZATION
The configuration file can be found in $XDG_CONFIG_HOME and offer the ability to 
change the default colors and number of lines to show.
.SH AUTHORS
Daniel Sandman <revoltism@gmail.com>
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH SEE ALSO
.BR pacman (8),
.BR yaourt (8)
.SH BUGS
Please report them. The source can be found at https://github.com/Almehdi/pachist.
